<?php
return [
    'section' => [
       'id'     => '_broadcasting_setting',
       'label'  => __('settings.broadcasting_setting'),
       'icon'   => '', 
    ],
    'fields' => [
        [
            'id'            => 'broadcasting_driver',
            'type'          => 'select',
            'class'         => '',
            'label_title'   => __('settings.broadcasting_driver'),
            'field_desc'    => __('settings.broadcasting_driver_desc'),
            'options'       => [
                'log'             => 'None',
                'reverb'          => 'Reverb',
                'pusher'          => 'Pusher',
            ],
            'default'       => 'log',
            'placeholder'   => __('settings.select_option'),
        ],
        [
            'id'            => 'pusher_divider',
            'type'          => 'info',
            'label_title'   => __('settings.pushadd_pusher_keys'),
            'label_desc'    => __('settings.pushadd_pusher_keys_desc'),
        ],
        [
            'id'            => 'pusher_app_id',
            'type'          => 'text',
            'class'         => '',
            'label_title'   => __('settings.pusher_app_id'),
            'field_desc'    => __('settings.pusher_app_id_desc'),
            'placeholder'   => __('settings.enter_pusher_app_id'),
        ],
        [
            'id'            => 'pusher_app_key',
            'type'          => 'text',
            'class'         => '',
            'label_title'   => __('settings.pusher_app_key'),
            'field_desc'    => __('settings.pusher_app_key_desc'),
            'placeholder'   => __('settings.enter_pusher_app_key'),
        ],
        [
            'id'            => 'pusher_app_secret',
            'type'          => 'text',
            'class'         => '',
            'label_title'   => __('settings.pusher_app_secret'),
            'field_desc'    => __('settings.pusher_app_secret_desc'),
            'placeholder'   => __('settings.enter_pusher_app_secret'),
        ],
        [
            'id'            => 'pusher_app_cluster',
            'type'          => 'text',
            'class'         => '',
            'label_title'   => __('settings.pusher_app_cluster'),
            'field_desc'    => __('settings.pusher_app_cluster_desc'),
            'placeholder'   => __('settings.enter_pusher_app_cluster'),
        ],
        
        [
            'id'            => 'reverb_divider',
            'type'          => 'info',
            'label_title'   => __('settings.pushadd_reverb_keys'),
            'label_desc'    => __('settings.pushadd_reverb_keys_desc'),
        ],
        [
            'id'            => 'reverb_app_id',
            'type'          => 'text',
            'class'         => '',
            'label_title'   => __('settings.reverb_app_id'),
            'field_desc'    => __('settings.reverb_app_id_desc'),
            'placeholder'   => __('settings.enter_reverb_app_id'),
        ],
        [
            'id'            => 'reverb_app_key',
            'type'          => 'text',
            'class'         => '',
            'label_title'   => __('settings.reverb_app_key'),
            'field_desc'    => __('settings.reverb_app_key_desc'),
            'placeholder'   => __('settings.enter_reverb_app_key'),
        ],
        [
            'id'            => 'reverb_app_secret',
            'type'          => 'text',
            'class'         => '',
            'label_title'   => __('settings.reverb_app_secret'),
            'field_desc'    => __('settings.reverb_app_secret_desc'),
            'placeholder'   => __('settings.enter_reverb_app_secret'),
        ],
        [
            'id'            => 'reverb_app_host',
            'type'          => 'text',
            'class'         => '',
            'label_title'   => __('settings.reverb_app_host'),
            'field_desc'    => __('settings.reverb_app_host_desc'),
            'placeholder'   => __('settings.enter_reverb_app_host'),
        ],
        [
            'id'            => 'reverb_app_port',
            'type'          => 'text',
            'class'         => '',
            'label_title'   => __('settings.reverb_app_port'),
            'field_desc'    => __('settings.reverb_app_port_desc'),
            'placeholder'   => __('settings.enter_reverb_app_port'),
        ],
        [
            'id'            => 'reverb_app_scheme',
            'type'          => 'text',
            'class'         => '',
            'label_title'   => __('settings.reverb_app_scheme'),
            'field_desc'    => __('settings.reverb_app_scheme_desc'),
            'placeholder'   => __('settings.enter_reverb_app_scheme'),
        ],
    ]
];