<?php

return [
    'section' => [
        'id'     => '_sidebar_menu',
        'label'  => __('admin/sidebar.sidebar_menu'),
        'tabs'   => true,
        'icon'   => '',
    ],
    'fields' => [
        [
            'id'            => 'dashboard_menu',
            'type'          => 'text',
            'tab_id'        => 'tutor_menu',
            'tab_title'     => __('settings.tutor_menu'),
            'value'         => '',
            'class'         => '',
            'label_title'   => __('settings.dashboard_menu_text'),
            'placeholder'   => __('settings.enter_dashboard_menu_text'),
        ],
        [
            'id'            => 'profile_settings_menu',
            'type'          => 'text',
            'tab_id'        => 'tutor_menu',
            'tab_title'     => __('settings.tutor_menu'),
            'value'         => '',
            'class'         => '',
            'label_title'   => __('settings.profile_settings_menu_text'),
            'placeholder'   => __('settings.enter_profile_settings_menu_text'),
        ],
        [
            'id'            => 'manage_bookings_menu',
            'type'          => 'text',
            'tab_id'        => 'tutor_menu',
            'tab_title'     => __('settings.tutor_menu'),
            'value'         => '',
            'class'         => '',
            'label_title'   => __('settings.manage_bookings_menu_text'),
            'placeholder'   => __('settings.enter_manage_bookings_menu_text'),
        ],
        [
            'id'            => 'inbox_menu',
            'type'          => 'text',
            'tab_id'        => 'tutor_menu',
            'tab_title'     => __('settings.tutor_menu'),
            'value'         => '',
            'class'         => '',
            'label_title'   => __('settings.inbox_menu_text'),
            'placeholder'   => __('settings.enter_inbox_menu_text'),
        ],
        [
            'id'            => 'payouts_menu',
            'type'          => 'text',
            'tab_id'        => 'tutor_menu',
            'tab_title'     => __('settings.tutor_menu'),
            'value'         => '',
            'class'         => '',
            'label_title'   => __('settings.payouts_menu_text'),
            'placeholder'   => __('settings.enter_payouts_menu_text'),
        ],
        [
            'id'            => 'invoices_menu',
            'type'          => 'text',
            'tab_id'        => 'tutor_menu',
            'tab_title'     => __('settings.tutor_menu'),
            'value'         => '',
            'class'         => '',
            'label_title'   => __('settings.invoices_menu_text'),
            'placeholder'   => __('settings.enter_invoices_menu_text'),
        ],
        [
            'id'            => 'disputes_menu',
            'type'          => 'text',
            'tab_id'        => 'tutor_menu',
            'tab_title'     => __('settings.tutor_menu'),
            'value'         => '',
            'class'         => '',
            'label_title'   => __('settings.disputes_menu_text'),
            'placeholder'   => __('settings.enter_disputes_menu_text'),
        ],
        // Student Menu
        [
            'id'            => 'student_profile_settings_menu',
            'type'          => 'text',
            'tab_id'        => 'student_menu',
            'tab_title'     => __('settings.student_menu'),
            'value'         => '',
            'class'         => '',
            'label_title'   => __('settings.profile_settings_menu_text'),
            'placeholder'   => __('settings.enter_profile_settings_menu_text'),
        ],
        [
            'id'            => 'my_bookings_menu',
            'type'          => 'text',
            'tab_id'        => 'student_menu',
            'tab_title'     => __('settings.student_menu'),
            'value'         => '',
            'class'         => '',
            'label_title'   => __('settings.my_bookings_menu_text'),
            'placeholder'   => __('settings.enter_my_bookings_menu_text'),
        ],
        [
            'id'            => 'find_tutors_menu',
            'type'          => 'text',
            'tab_id'        => 'student_menu',
            'tab_title'     => __('settings.student_menu'),
            'value'         => '',
            'class'         => '',
            'label_title'   => __('settings.find_tutors_menu_text'),
            'placeholder'   => __('settings.enter_find_tutors_menu_text'),
        ],
        [
            'id'            => 'student_inbox_menu',
            'type'          => 'text',
            'tab_id'        => 'student_menu',
            'tab_title'     => __('settings.student_menu'),
            'value'         => '',
            'class'         => '',
            'label_title'   => __('settings.inbox_menu_text'),
            'placeholder'   => __('settings.enter_inbox_menu_text'),
        ],
        [
            'id'            => 'favourites_menu',
            'type'          => 'text',
            'tab_id'        => 'student_menu',
            'tab_title'     => __('settings.student_menu'),
            'value'         => '',
            'class'         => '',
            'label_title'   => __('settings.favourites_menu_text'),
            'placeholder'   => __('settings.enter_favourites_menu_text'),
        ],
        [
            'id'            => 'student_invoices_menu',
            'type'          => 'text',
            'tab_id'        => 'student_menu',
            'tab_title'     => __('settings.student_menu'),
            'value'         => '',
            'class'         => '',
            'label_title'   => __('settings.invoices_menu_text'),
            'placeholder'   => __('settings.enter_invoices_menu_text'),
        ],
        [
            'id'            => 'student_disputes_menu',
            'type'          => 'text',
            'tab_id'        => 'student_menu',
            'tab_title'     => __('settings.student_menu'),
            'value'         => '',
            'class'         => '',
            'label_title'   => __('settings.disputes_menu_text'),
            'placeholder'   => __('settings.enter_disputes_menu_text'),
        ],
        [
            'id'            => 'billing_details_menu',
            'type'          => 'text',
            'tab_id'        => 'student_menu',
            'tab_title'     => __('settings.student_menu'),
            'value'         => '',
            'class'         => '',
            'label_title'   => __('settings.billing_details_menu_text'),
            'placeholder'   => __('settings.enter_billing_details_menu_text'),
        ],
    ]
];
